"""Init tables

Revision ID: ee26ff84cd24
Revises: 
Create Date: 2024-06-30 10:52:40.923439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee26ff84cd24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('mail_ru_pass', sa.String(), nullable=True),
    sa.Column('gmail_pass', sa.String(), nullable=True),
    sa.Column('yandex_pass', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('login')
    )
    op.create_table('email',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('send_from', sa.String(), nullable=False),
    sa.Column('email_header', sa.String(), nullable=True),
    sa.Column('receive_date', sa.DateTime(), nullable=False),
    sa.Column('email_text', sa.String(), nullable=False),
    sa.Column('attached_files', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    op.drop_table('user')
    # ### end Alembic commands ###
